package com.neteasecommunity.james.model;

import java.io.Serializable;

public class User  implements Serializable {
    private static final long serialVersionUID = 6552551566752477983L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Fri Feb 28 20:51:08 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbg.generated Fri Feb 28 20:51:08 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Fri Feb 28 20:51:08 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gmt_create
     *
     * @mbg.generated Fri Feb 28 20:51:08 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gmt_modified
     *
     * @mbg.generated Fri Feb 28 20:51:08 CST 2020
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.avatar_url
     *
     * @mbg.generated Fri Feb 28 20:51:08 CST 2020
     */
    private String avatarUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.rank
     *
     * @mbg.generated Fri Feb 28 20:51:08 CST 2020
     */
    private Integer rank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.concerns
     *
     * @mbg.generated Fri Feb 28 20:51:08 CST 2020
     */
    private Integer concerns;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.followers
     *
     * @mbg.generated Fri Feb 28 20:51:08 CST 2020
     */
    private Integer followers;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Fri Feb 28 20:51:08 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Fri Feb 28 20:51:08 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbg.generated Fri Feb 28 20:51:08 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbg.generated Fri Feb 28 20:51:08 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated Fri Feb 28 20:51:08 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated Fri Feb 28 20:51:08 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.gmt_create
     *
     * @return the value of user.gmt_create
     *
     * @mbg.generated Fri Feb 28 20:51:08 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.gmt_create
     *
     * @param gmtCreate the value for user.gmt_create
     *
     * @mbg.generated Fri Feb 28 20:51:08 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.gmt_modified
     *
     * @return the value of user.gmt_modified
     *
     * @mbg.generated Fri Feb 28 20:51:08 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.gmt_modified
     *
     * @param gmtModified the value for user.gmt_modified
     *
     * @mbg.generated Fri Feb 28 20:51:08 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.avatar_url
     *
     * @return the value of user.avatar_url
     *
     * @mbg.generated Fri Feb 28 20:51:08 CST 2020
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.avatar_url
     *
     * @param avatarUrl the value for user.avatar_url
     *
     * @mbg.generated Fri Feb 28 20:51:08 CST 2020
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.rank
     *
     * @return the value of user.rank
     *
     * @mbg.generated Fri Feb 28 20:51:08 CST 2020
     */
    public Integer getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.rank
     *
     * @param rank the value for user.rank
     *
     * @mbg.generated Fri Feb 28 20:51:08 CST 2020
     */
    public void setRank(Integer rank) {
        this.rank = rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.concerns
     *
     * @return the value of user.concerns
     *
     * @mbg.generated Fri Feb 28 20:51:08 CST 2020
     */
    public Integer getConcerns() {
        return concerns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.concerns
     *
     * @param concerns the value for user.concerns
     *
     * @mbg.generated Fri Feb 28 20:51:08 CST 2020
     */
    public void setConcerns(Integer concerns) {
        this.concerns = concerns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.followers
     *
     * @return the value of user.followers
     *
     * @mbg.generated Fri Feb 28 20:51:08 CST 2020
     */
    public Integer getFollowers() {
        return followers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.followers
     *
     * @param followers the value for user.followers
     *
     * @mbg.generated Fri Feb 28 20:51:08 CST 2020
     */
    public void setFollowers(Integer followers) {
        this.followers = followers;
    }
}