package com.neteasecommunity.james.mapper;

import com.neteasecommunity.james.model.Relationship;
import com.neteasecommunity.james.model.RelationshipExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Component;

@Component
public interface RelationshipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationship
     *
     * @mbg.generated Sun Mar 08 21:50:07 CST 2020
     */
    long countByExample(RelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationship
     *
     * @mbg.generated Sun Mar 08 21:50:07 CST 2020
     */
    int deleteByExample(RelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationship
     *
     * @mbg.generated Sun Mar 08 21:50:07 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationship
     *
     * @mbg.generated Sun Mar 08 21:50:07 CST 2020
     */
    int insert(Relationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationship
     *
     * @mbg.generated Sun Mar 08 21:50:07 CST 2020
     */
    int insertSelective(Relationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationship
     *
     * @mbg.generated Sun Mar 08 21:50:07 CST 2020
     */
    List<Relationship> selectByExampleWithRowbounds(RelationshipExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationship
     *
     * @mbg.generated Sun Mar 08 21:50:07 CST 2020
     */
    List<Relationship> selectByExample(RelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationship
     *
     * @mbg.generated Sun Mar 08 21:50:07 CST 2020
     */
    Relationship selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationship
     *
     * @mbg.generated Sun Mar 08 21:50:07 CST 2020
     */
    int updateByExampleSelective(@Param("record") Relationship record, @Param("example") RelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationship
     *
     * @mbg.generated Sun Mar 08 21:50:07 CST 2020
     */
    int updateByExample(@Param("record") Relationship record, @Param("example") RelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationship
     *
     * @mbg.generated Sun Mar 08 21:50:07 CST 2020
     */
    int updateByPrimaryKeySelective(Relationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationship
     *
     * @mbg.generated Sun Mar 08 21:50:07 CST 2020
     */
    int updateByPrimaryKey(Relationship record);
}